#!/bin/bash
case $1 in
	up)
	  pamixer -i 5
	  dunstify --urgency=LOW -r 92030 "  ses $(pamixer --get-volume-human)" 
	;;

	down)
	  pamixer -d 5
	  dunstify --urgency=LOW -r 92030 "  ses $(pamixer --get-volume-human)"
	;;

	full)
	  pamixer --set-volume 100
	  dunstify --urgency=LOW -r 92030 "  ses $(pamixer --get-volume-human)"
	;;

	off)
	  pamixer --set-volume 0
	  dunstify --urgency=LOW -r 92030 "  ses $(pamixer --get-volume-human)"
	;;

	toggle)
	  case $(pamixer --get-volume-human) in
	  	muted)
	 	   pamixer -t
	  	   dunstify --urgency=LOW -r 92030 "  $(pamixer --get-volume-human)"
		;;

		*)
		 pamixer -t
		 dunstify --urgency=LOW -r 92030 "  susturuldu"
		;;
	  esac
	;;
esac
