#!/bin/bash
case $1 in
	down)
	  xbacklight -dec 5 -steps 1
	  dunstify --urgency=LOW -r 64983 "  parlaklık %`xbacklight | sed 's/[.].*//g'`"
	;;

	up)
	  xbacklight -inc 5 -steps 1
	  dunstify --urgency=LOW -r 64983 "  parlaklık %$(xbacklight | sed 's/[.].*//g')"
	;;

	full)
	  xbacklight -set 100
	  dunstify --urgency=LOW -r 64983 "  parlaklık %$(xbacklight | sed 's/[.].*//g')"
	;;

	off)
	  xbacklight -set 1
	  dunstify --urgency=LOW -r 64983 " ekran karartıldı"
	;;


	*)
	  dunstify --urgency=LOW -r 64983 "  parlaklık %$(xbacklight | sed 's/[.].*//g')"
	;;
esac
