#!/bin/bash
case $1 in
	--select | -s)
		ffmpeg $(slop -f '-video_size %wx%h -framerate 60 -f x11grab -i :0.0+%x,%y') /home/skarphet/vid/sc/$(date +'%Y-%m-%d_%H.%M.%S').mp4
	;;

	--fullscreen | -f)
		ffmpeg -video_size 1366x768 -framerate 60 -f x11grab -i :0.0 /home/skarphet/vid/sc/$(date +'%Y-%m-%d_%H.%M.%S').mp4
	;;

	*)
		echo
		echo -e "\e[1mscreencast"
		echo -e " \e[0;39mscreencast {-f --fullscreen}    record fullscreen"
		echo -e " \e[0;39mscreencast {-s --select}        record the selected window"
		echo
	;;
esac
