#!/bin/sh

# polybar
polybar middle &

# feh background
$HOME/.config/feh/.fehbg &

# key bindings
sxhkd &

# picom
picom --experimental-backends -b

# dunst
dunst > /dev/null 2>&1

# set root pointer
xsetroot -cursor_name left_ptr

# Set some bsp specific stuff
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 &
startup

# bspwm settings
bspc config window_gap 12
bspc config top_padding 43
bspc config right_padding 0
bspc config bottom_padding 12
bspc config left_padding 0

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width 0
bspc config focused_border_color "#a3b8ef"
bspc config normal_border_color  "#121212"

# some window rules
bspc rule -a feh state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Spotify desktop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a signal-desktop desktop='^8'
bspc rule -a nextcloud desktop='^7' state=tiled

