#!/bin/sh

# Set some bsp specific stuff
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 &

# bspwm settings
bspc config window_gap 4
bspc config top_padding 20
bspc config right_padding -4
bspc config bottom_padding -4
bspc config left_padding -4

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true

bspc config pointer_modifier mod4
bspc config click_to_focus true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config border_width 0
bspc config focused_border_color "#a3b8ef"
bspc config normal_border_color  "#121212"

# some window rules
bspc rule -a feh state=floating follow=on
bspc rule -a mpv state=floating
bspc rule -a Spotify desktop='^7'
bspc rule -a discord desktop='^8'
bspc rule -a "Signal Beta" desktop='^8'
bspc rule -a "WhatsApp - Google Chrome" desktop='^8'
bspc rule -a nextcloud desktop='^7' state=tiled
bspc rule -a KeePassXC state=floating
bspc rule -a zoom state=floating
bspc rule -a "Tor Browser" state=floating

# polybar
~/.config/polybar/launch.sh &

# pywal
wal -qst --saturate=1.0 -i $HOME/.wallpapers &

# feh background
# $HOME/.config/feh/.fehbg &

# key bindings
sxhkd &

# picom
picom --experimental-backends -b

# dunst
dunst > /dev/null 2>&1

# set root pointer
xsetroot -cursor_name left_ptr
